{
  "help": "MBLER\nMinecraft Bedrock Edition\nAddon Bulider In Nodejs\nnodejs build tools on bedrock version of minecraft\nSolve the problem of checking documents everywhere to configure api version\nUsage: node index.js [command]\n* You can also omit the node prefix after npm link link\nCommands: dev, install, build, init, version, -v, web_edit, clean, checkout, -c, -i, v, create, recache, lang\nHelp command:\n  help\n    Show help information\n    The second parameter is the name of the command to be queried or empty\n    Alias: -h, -help\n git https://github.com/RuanhoR/mbler/",
  "config_invalid": "Non-GameLib projects",
  "err_bulid": "Build error",
  "uncommand": "Invalid command",
  "s0": "Operation successful",
  "noGit": "Git security restrictions detected\nGit is rejecting the operation because the directory might not belong to the current user or be in a system-protected path.\nPlease select a processing method:\n\n1: Only add the current directory to the trusted zone (recommended, safe)\n2: Globally trust all directories (not recommended, but convenient)\n3: Cancel operation",
  "SameDes": "Dependencies with the same name",
  "invalidConfig": "Invalid configuration",
  "inited": "Already initialized",
  "noGitRepo": "The requested git repository was not specified and the installation failed.",
  "invalidDes": "invalid dependency",
  "workPackV": "Current working directory package version:",
  "cleanFinally": "Clean build successful",
  "noCommandTip": "Do you want to express:",
  "init": {
    "name": "Project name:",
    "desc": "Project description:",
    "useMcVersion": "Supported minecraft versions:",
    "useSapi": "Use Script API? (Y/N)",
    "useTs": "Using TypeScript? (Y/N)",
    "InputFormatErr": "It is not the correct version number in x.x.x format, please re-enter it.",
    "main": "Main script path (such as ./index.js):",
    "useUi": "Use UI? (Y/N)",
    "ReInput": "Not meeting specifications. Try again:"
  },
  "dev": {
    "start": "Start monitoring the build in real time. The following is the first build.",
    "start_d": "Start an incremental build",
    "tip": "Listen for changes:"
  },
  "installGit": {
    "NoPackage": "This GIT repository does not contain a properly configured mbler",
    "InstallFinally": "Installation completed",
    "HadBeen": "There is already a dependent package with the same package name. Do you want to replace it? Y/N",
    "SetContent": "Modifying index table"
  },
  "vm": {
    "shouldNotImp": "Importing a module is prohibited because it can be used in unsafe ways",
    "runScriptErr": "Error running script, error stack"
  },
  "build": {
    "build_info_header": "--- Build information list ---",
    "project_path": "Project path:",
    "output_dir": "Output directory:",
    "minify_enabled": "Enable compression:",
    "build_time": "Build time:",
    "build_success": "Build successfully. Time taken:",
    "build_failed": "Build failed",
    "config_invalid": "Invalid configuration",
    "package_file_missing_fields": "Missing fields: required fields [\"name\",\"description\",\"version\",\"mcVersion\"]",
    "script_main_entry_missing": "script is enabled, but main entry file is not specified",
    "subpack_folder_not_found": "{id} sub-package folder does not exist, packaging failed",
    "subpack_processing_failed": "Subpackage {id} failed to process: {error}",
    "includes_not_array": "includes.json is not an array, skip resource copying",
    "ts_no_files": "No .ts files found, skipping TypeScript compilation",
    "ts_diagnostics": "{file} ({line},{character}): {message}",
    "ts_compilation_error": "Error compiling TypeScript",
    "no_ts_files_skip": "No .ts files found, skipping TypeScript compilation",
    "copying_subpack_script": "Subpackage script directory copied",
    "copying_subpack_resources": "Copying subpackage other resources",
    "removing_js_files": "Remove the .js files in the script directory",
    "copying_compiled_ts": "Copy the compiled TypeScript file",
    "minification_error": "Code compression failed",
    "temp_mod_init": "Initialize temporary module directory",
    "script_entry_required": "script is enabled but the main entry is not set",
    "invalid_script_entry": "The main entry file is empty or invalid",
    "module_copy_success": "Module copied to output directory",
    "invalid_subpack_type": "subpack is not an object, skip processing",
    "invalid_includes_type": "includes.json is not an array, skip resource copying",
    "handle_includes_info": "Handle includes resource copy",
    "minification_skipped": "includes.json is not an array, skips code compression",
    "remove_js_files_info": "Remove compiled .js files (e.g. from ts)",
    "process_minification": "Start code compression processing",
    "copy_compiled_ts_only": "Copy only compiled ts files",
    "temp_mod_usage": "Using a temporary directory to handle TypeScript compilation",
    "build_failed_catch": "The build process terminated abnormally",
    "error_message_log": "error message:",
    "exit_with_code": "Process exits with code:",
    "class_pri_locked": "Lock key attributes within a class",
    "object_pri_enforced": "Setting object properties is not enumerable",
    "no_resources": "Resource package resource not found, resource compilation skipped",
    "ziped": "The zip compression is complete and you can directly import the game.\nThe mcaddon file is in:",
    "tip_dist": "Packaging mode:"
  },
  "buildBase": {
    "npm_deps_skipped_no_json": "npm dependency not found, skip installation",
    "build_time": "Build time",
    "cannot_read_project_config": "Unable to read project configuration file",
    "invalid_project_config_format": "Project configuration file format is invalid",
    "starting_npm_install": "Start installing npm dependencies",
    "npm_install_completed": "Dependency installation completed",
    "npm_install_exit_code": "npm install exit code:",
    "npm_install_error": "npmInstall error",
    "calculating_sha1": "Calculate file SHA1 hash value",
    "file_not_exist": "File does not exist",
    "config_hash_stored": "Configuration hash stored",
    "package_hash_stored": "Packet hash stored",
    "config_changed": "Configuration has changed",
    "package_changed": "Package has changed",
    "saving_current_hash": "Save current hash to cache",
    "removing_js_files": "Remove the .js files in the script directory",
    "removing_js_error_ignored": "Remove .js file error, ignored",
    "removing_npm_des": "Remove npm dependency description",
    "module_not_included": "Module not included, skip deletion",
    "recursive_remove_js": "Recursively remove Js files",
    "reading_file_content": "Read file contents"
  },
  "commands": {
    "list": {
      "0": "dev",
      "1": "install",
      "2": "build",
      "3": "init",
      "4": "version",
      "5": "-v",
      "6": "web_edit",
      "7": "clean",
      "8": "checkout",
      "9": "-c",
      "10": "-i",
      "11": "v",
      "12": "create",
      "13": "recache",
      "14": "lang"
    },
    "dev": "mblerdev\nMonitor files and repackage when modified",
    "build": "mbler build\nPackage the project, package the mbler project into a standard mcbe behavior package, see the document for details on the mbler project",
    "init": "mbler init\nInitialization path configuration file, created interactively from the command line, alias: -i",
    "version": "mbler version [null | x.x.x]\nView or set the package version of the current working directory",
    "-c": "$checkout",
    "-i": "$init",
    "-v": "$v",
    "v": "mbler [v/-v]\nCheck the version of the mbler tool itself",
    "checkout": "mbler [checkout/-c] [null | PATH]\nView (when the second parameter is null) or switch the working directory",
    "web_edit": "mbler web_edit\nOpen the text editor of the local HTTP working directory. It is not recommended to use during development.",
    "create": "mbler create [npm package name | git url | path]\nAfter downloading from the specified source (with cache), create the template package in the sandbox vm, similar to npm create",
    "recache": "mbler recache\nreset cache",
    "lang": "mbler lang [lang name]\nSet the language, such as mbler lang zh_CN\nThe current languages are\n 1. zh 中文\n 2. en English",
    "install": "mbler install [modulesName[]]\nWhen installing a module, the modules declared in the configuration will be scanned."
  }
}